import type { Profile } from "@/types/profile"

export const portfolioUpdatedAt = "2026-08-12"

// Swap to https://jefmonjor.dev once the domain is purchased and connected.
export const siteUrl = "https://portfolio-omega-drab-fsvg6tmcd2.vercel.app"

export const profileTimeZone = "Europe/Andorra"

export const profile: Profile = {
  name: "Jefferson Montesdeoca Jordán",
  shortName: "Jefferson Montesdeoca",
  location: "Andorra la Vella, Andorra",
  timezone: "CET / CEST",
  since: "2019",
  focus: [
    "Java 21",
    "Spring Boot 3",
    "Hexagonal Architecture",
    "Microservices",
    "Next.js",
    "Claude API",
    "AI agents",
  ],
  marquee: [
    "Java",
    "Spring Boot",
    "Hibernate",
    "Microservices",
    "REST APIs",
    "Docker",
    "Kubernetes",
    "OpenShift",
    "Jenkins",
    "Keycloak",
    "OAuth2",
    "Oracle",
    "DB2",
    "PostgreSQL",
    "Cassandra",
    "Hadoop",
    "Spark",
    "React",
    "Next.js",
    "TypeScript",
    "Claude API",
    "MCP",
    "Vercel AI SDK",
  ],
  socials: [
    {
      // Address assembled client-side in lib/email.ts to keep it out of
      // the static HTML (spam-scraper protection).
      kind: "email",
      href: "#contact",
      handle: "",
    },
    {
      kind: "linkedin",
      href: "https://www.linkedin.com/in/jefmonjor",
      handle: "jefmonjor",
    },
    {
      kind: "github",
      href: "https://github.com/jefmonjor",
      handle: "jefmonjor",
    },
  ],
  experience: [
    {
      id: "andbank-2024",
      organization: "Andbank",
      location: "Andorra la Vella, Andorra",
      startISO: "2024-09",
      endISO: "present",
      stack: [
        "Java 21",
        "Spring Boot 3",
        "OpenShift",
        "Keycloak",
        "DB2",
        "COBOL/AS400",
        "SonarQube",
      ],
    },
    {
      id: "elabogado-2022",
      organization: "elAbogado",
      location: "Barcelona, Spain",
      startISO: "2022-03",
      endISO: "2024-09",
      stack: ["Java", "Spring Boot", "React", "MySQL", "REST APIs", "WordPress"],
    },
    {
      id: "zemsania-2021",
      organization: "Zemsania",
      location: "Madrid, Spain",
      startISO: "2021-07",
      endISO: "2022-04",
      stack: ["Java", "Spring Boot", "Microservices", "OpenAPI", "Jira · Confluence"],
    },
    {
      id: "keapps-2020",
      organization: "Keapps (Atos)",
      location: "Seville, Spain",
      startISO: "2020-07",
      endISO: "2021-07",
      stack: ["Java", "Hadoop", "Spark", "Cassandra", "HDFS · YARN", "SQL"],
    },
    {
      id: "ayesa-2019",
      organization: "Ayesa",
      location: "Seville, Spain",
      startISO: "2019-08",
      endISO: "2020-04",
      stack: ["Java", "Hadoop", "MapReduce", "S3", "JSP · PrimeFaces", "SOAP/XML"],
    },
  ],
  skills: [
    {
      id: "languages",
      items: ["Java (8 → 21)", "TypeScript", "JavaScript", "Python", "SQL"],
    },
    {
      id: "backend",
      items: [
        "Spring Boot 3",
        "Hibernate",
        "JPA",
        "REST / SOAP",
        "Node.js",
        "FastAPI",
        "Hexagonal Architecture",
        "Microservices",
      ],
    },
    {
      id: "frontend",
      items: ["React", "Next.js", "Tailwind CSS", "shadcn/ui", "Bootstrap", "JSP · PrimeFaces", "WordPress"],
    },
    {
      id: "data",
      items: [
        "Oracle · PL/SQL",
        "DB2",
        "PostgreSQL",
        "MySQL",
        "Supabase",
        "Neon",
        "Redis · Upstash",
        "Backblaze B2",
        "Cassandra",
        "Hadoop · HDFS · YARN",
        "Spark · MapReduce",
        "S3",
      ],
    },
    {
      id: "cloud",
      items: [
        "Docker",
        "Kubernetes",
        "OpenShift (OCP4)",
        "VPS propio · Docker",
        "Vercel",
        "Google Cloud Run",
        "Cloud Build",
        "GitHub Actions",
        "Brevo",
        "Twilio",
        "Serverless",
        "Jenkins",
        "CI/CD",
        "Keycloak",
        "OAuth2",
        "Azure",
      ],
    },
    {
      id: "ai",
      items: [
        "Claude · Claude API",
        "Claude Code",
        "Codex",
        "ChatGPT",
        "Gemini",
        "Gemini Code Assist",
        "Antigravity IDE",
        "Orca",
        "SDD · spec-kit",
        "MCP workflows",
        "Vercel AI SDK",
        "AI agents",
      ],
    },
    {
      id: "practice",
      items: ["architecture", "vendor-management", "ai-augmented", "scrum"],
    },
  ],
  projects: [
    {
      id: "othertales",
      stack: [
        "Flutter",
        "Riverpod",
        "Java 21",
        "Spring Boot 3",
        "PostgreSQL",
        "Docker",
      ],
    },
    {
      id: "trasolido",
      stack: [
        "Java 21",
        "Spring Boot 3",
        "Neon",
        "Upstash Redis",
        "Claude API",
        "VERI*FACTU",
        "Cloud Run",
        "Vercel",
      ],
    },
    {
      id: "porrix",
      stack: ["Next.js", "PostgreSQL", "PWA", "Docker", "VPS propio", "ES · EN · CA"],
    },
    {
      id: "corte1d",
      stack: ["Next.js", "Neon", "PWA", "ExcelJS", "PDFKit", "Backblaze B2", "AI agents"],
    },
    {
      id: "tavory",
      stack: ["Next.js 16", "Supabase", "PostGIS", "Stripe", "Mapbox", "AI OCR"],
    },
    {
      id: "wedding",
      stack: ["Next.js", "shadcn/ui", "Turnstile", "Playwright", "Vercel"],
    },
    {
      id: "headless-commerce",
      stack: ["MedusaJS", "Next.js", "PostgreSQL · pgvector", "Redis", "Docker"],
    },
    {
      id: "contactqr",
      stack: ["Astro", "QR · vCard"],
    },
    {
      id: "portfolio",
      url: siteUrl,
      repo: "https://github.com/jefmonjor/portfolio",
      images: [
        "/projects/portfolio/01.webp",
        "/projects/portfolio/02.webp",
        "/projects/portfolio/03.webp",
      ],
      stack: [
        "Next.js",
        "TypeScript",
        "tRPC",
        "Zod",
        "Tailwind CSS",
        "shadcn/ui",
        "next-intl",
        "Motion",
      ],
    },
  ],
  education: [
    {
      id: "smpc-cert",
      organization: "SCRUMstudy",
      dates: "2023",
    },
    {
      id: "beng-software",
      organization: "Universidad de Sevilla",
      dates: "2014 — 2018",
    },
  ],
  languages: [{ id: "es" }, { id: "en" }],
}
