import type { Profile } from "@/types/profile"

export const portfolioUpdatedAt = "2026-05-20"

export const profileTimeZone = "Europe/Andorra"

export const profile: Profile = {
  name: "Luis Enrique Pina Herce",
  shortName: "Enrique Pina",
  location: "Escaldes-Engordany, Andorra",
  timezone: "CET / CEST",
  since: "2020",
  focus: [
    "TypeScript",
    "Next.js",
    "NestJS",
    "Node.js",
    "Python",
    "Data pipelines",
    "Serverless architecture",
  ],
  marquee: [
    "TypeScript",
    "Next.js",
    "NestJS",
    "React",
    "Node.js",
    "PostgreSQL",
    "tRPC",
    "Tailwind",
    "MongoDB",
    "MySQL",
    "Express",
    "Zod",
    "React Query",
    "Docker",
    "Terraform",
    "Serverless",
    "ECS",
    "AWS Lambda",
    "S3",
  ],
  socials: [
    {
      kind: "email",
      href: "mailto:luisenrique.ph97@gmail.com?subject=Hello%20Enrique",
      handle: "luisenrique.ph97@gmail.com",
    },
    {
      kind: "linkedin",
      href: "https://www.linkedin.com/in/luis-enrique-pina-herce-b39740197",
      handle: "luis-enrique-pina-herce",
    },
  ],
  experience: [
    {
      id: "hotelgest-2025",
      organization: "hotelgest",
      location: "Escaldes-Engordany, Andorra",
      startISO: "2025-04",
      endISO: "present",
      stack: ["TypeScript", "Node.js", "React", "PostgreSQL"],
    },
    {
      id: "andbank-2024",
      organization: "Andbank",
      location: "Andorra",
      startISO: "2024-10",
      endISO: "2025-04",
      stack: ["TypeScript", "Node.js", "SQL"],
    },
    {
      id: "eosol-software-manager-2023",
      organization: "EOSOL",
      location: "Mutilva, Navarre, Spain",
      startISO: "2023-08",
      endISO: "2024-10",
      stack: ["TypeScript", "NestJS", "Next.js", "PostgreSQL"],
    },
    {
      id: "eosol-software-developer-2022",
      organization: "EOSOL",
      location: "Navarre, Spain",
      startISO: "2022-07",
      endISO: "2023-08",
      stack: ["Node.js", "NestJS", "React", "TypeScript"],
    },
    {
      id: "eosol-data-engineer-2021",
      organization: "EOSOL",
      location: "Navarre, Spain",
      startISO: "2021-03",
      endISO: "2022-06",
      stack: ["Python", "SQL", "Kafka", "MongoDB"],
    },
    {
      id: "upna-research-2020",
      organization: "Universidad Pública de Navarra",
      location: "Navarre, Spain",
      startISO: "2020-07",
      endISO: "2020-12",
      stack: [
        "Hortonworks",
        "Sqoop",
        "Hive",
        "Kafka",
        "MongoDB",
        "MySQL",
        "Express",
      ],
    },
  ],
  skills: [
    {
      id: "languages",
      items: ["TypeScript", "JavaScript", "Python", "SQL"],
    },
    {
      id: "frontend",
      items: ["React", "Next.js", "Tailwind CSS", "shadcn/ui", "React Query"],
    },
    {
      id: "backend",
      items: ["Node.js", "NestJS", "Express", "tRPC", "Zod"],
    },
    {
      id: "data",
      items: ["PostgreSQL", "MySQL", "MongoDB", "Kafka", "Hive", "Sqoop"],
    },
    {
      id: "cloud",
      items: [
        "Docker",
        "Terraform",
        "AWS Lambda",
        "AWS SAM",
        "AWS ECS",
        "AWS Glue",
        "AWS Athena",
        "Step Functions",
        "SQS",
        "S3",
        "SageMaker",
        "GitHub Actions",
      ],
    },
    {
      id: "practice",
      items: ["spec-driven", "type-first", "code-review"],
    },
  ],
  projects: [
    {
      id: "apidex",
      url: "https://apidex.mdbep.dev",
      stack: [
        "Next.js",
        "TypeScript",
        "tRPC",
        "Zod",
        "Tailwind",
        "shadcn/ui",
        "AWS S3",
        "DynamoDB",
      ],
    },
    {
      id: "andllar",
      url: "https://andllar.com",
      stack: [
        "Next.js",
        "TypeScript",
        "Prisma",
        "Supabase",
        "Mapbox",
        "Tailwind",
        "React Query",
        "AWS S3",
      ],
    },
    {
      id: "sowify-admin",
      stack: [
        "Next.js",
        "TypeScript",
        "tRPC",
        "Prisma",
        "MongoDB",
        "Zod",
        "Tailwind",
        "React PDF",
        "better-auth",
        "AWS S3",
      ],
    },
    {
      id: "sowify-landing",
      url: "https://www.sowifyglobalsolutions.com/es",
      stack: [
        "Next.js",
        "TypeScript",
        "next-intl",
        "Tailwind CSS",
        "shadcn/ui",
        "Framer Motion",
        "Radix UI",
        "SEO metadata",
      ],
    },
  ],
  education: [
    {
      id: "msc-data-science",
      organization: "Universidad Nacional",
      dates: "2020 — 2022",
    },
    {
      id: "beng-computer-engineering",
      organization: "Universidad Pública de Navarra",
      dates: "2015 — 2020",
    },
  ],
  languages: [{ id: "es" }, { id: "en" }],
}
